name: Publish rust_py Docker image

on:
  workflow_dispatch:
    inputs:
      rust_version:
        description: 'Version of Rust to use in Dockerfile'
        required: true
        default: 1.59
      python_version:
        description: 'Version of Python to use in Dockerfile'
        required: true
        default: 3.9

jobs:
  push_to_gh_registry:
      name: Push Docker image to GitHub Packages
      runs-on: ubuntu-latest

      steps:
        - name: Check out the repo
          uses: actions/checkout@v2

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Log in to GitHub Container Registry
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ secrets.CR_USER }}
            password: ${{ secrets.CR_PAT }}

        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: .
            file: ./Dockerfile.rust_py
            push: true
            build-args: |
              rust_version=${{ github.event.inputs.rust_version }}
              python_version=${{ github.event.inputs.python_version }}
            tags: |
              ghcr.io/reddit/rust_py:${{ github.event.inputs.rust_version }}_${{ github.event.inputs.python_version }}
